{% set version = "2.0.2" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-pkgconfig
  version: {{ version|replace("-", "_") }}

source:
  fn: pkgconfig_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/pkgconfig_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/pkgconfig/pkgconfig_{{ version }}.tar.gz
  sha256: 25997754d1adbe7a251e3bf9879bb52dced27dd8b84767d558f0f644ca8d69ca

build:
  number: 0
  skip: true  # [win32]

  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('pkgconfig')"  # [not win]
    - "\"%R%\" -e \"library('pkgconfig')\""  # [win]

about:
  home: https://github.com/gaborcsardi/pkgconfig
  license: MIT
  summary: Set configuration options on a per-package basis. Options set by a given package only
    apply to that package, other packages are unaffected.
  license_family: MIT

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
