appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: wCKia78X7+ntYTLmIEuhtcmQXx+BXG5sOq6jNRY0futa31lMGaHVHsiwSn9ZuIaLT/WzTv22HUhhuBUgFM5kwhmcNWDD8QXa4oFXsmvoTT1bxmLLO9dtQN0HSARAmGno5/Jj3V7pZBvfyq+Ef/32JjKEkk5jm6p6f2doslmwisaF9CPiH1MEZi7z3F1b2QK97/2sHGG71tupOiQ8zlAB1neB7Zz3zpJ7VwR6zj3Og4ItLXQq1iKCqxJ3MN0OEAgXG1HEBWVGW5XmsEJUct9eLfsZ4txShHPepDoTeQ7WvRknRX2jQaIUYjLcu7FSjB4i7+AQByP5wRC7R4Hl1MXtXWi9EgHAhQFgcCtFc+hwJXT2zdXyV73988Gx94b2o2ACri1psV3AbjqFEK/T/vxUURUy8MMu06TCVDIXq3Ok4b3SBLpFHqJ78WG2ZPv8Z7qvhGdosClCtoNSNLIsE8VcK1JV2BEF5+ZeFxdaRkTvRXU/B/OUE6PxelMZC1Bg1Lvg+XWFNtzgFeeJ7uYG2zvS3bfhXOUnPHAjYlpSXmgRVRUnVxRQMGcXdIi5FfghZ6UHdcwPC49sVcSrr5ehfQ8ppu7eqW3n5noucC6rcRdI2WT87hL1lbB2pMW98x+rqE4tsMPxOzTQ2567/tz+tS72lJ2NJFMWMHYqyMnPJJG37as=}
